# Generated by Django 5.0.6 on 2024-06-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_estudiante_curso_remove_profesor_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name_plural': 'cursos'},
        ),
    ]
